
eureka: 
  client: 
    serviceUrl: 
      defaultZone: "http://localhost:8091/eureka"
instance: 
  preferIpAddress: true
server: 
  port: 8094
spring: 
  application: 
    name: cartservice
